### ISSUE TITLE
What is AUTH_TOKEN ?

### ISSUE THREAD

**Issue by raspbeguy** [NeroBurner/googleplayupdater#4]
Hi,
I am trying to use your program. I have to fill my `config.py` but I miss something. What is the parameter `AUTH_TOKEN` and how could I know its value? It isn't even evocated in your documentation.
I tried to keep it with the default value `"yyyyyyyyy"` but when I try to run it I've got the following error (not sure if it's linked):

```
Traceback (most recent call last):
  File "/usr/local/bin/googleplayupdater", line 9, in <module>
    load_entry_point('googleplayupdater==0.1.2', 'console_scripts', 'googleplayupdater')()
  File "/usr/local/lib/python3.5/dist-packages/googleplayupdater-0.1.2-py3.5.egg/googleplayupdater/gp_update.py", line 167, in main
  File "/usr/local/lib/python3.5/dist-packages/googleplayupdater-0.1.2-py3.5.egg/googleplayupdater/gp_update.py", line 101, in update
  File "/usr/local/lib/python3.5/dist-packages/googleplayupdater-0.1.2-py3.5.egg/googleplay_api/googleplay.py", line 243, in details
  File "/usr/local/lib/python3.5/dist-packages/googleplayupdater-0.1.2-py3.5.egg/googleplay_api/googleplay.py", line 217, in executeRequestApi2
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 712, in FromString
    message.MergeFromString(s)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1011, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag
```

Thanks for your attention.

**Comment by NeroBurner** [comment]
The `AUTH_TOKEN` is unfortunately not implemented. It was thought as replacement of email and password in plain text. set it to `None`, then google-api will just use your email and password

**Comment by raspbeguy** [comment]
OK, so I will have to delete `AUTH_TOKEN` from this code:

```
if ANDROID_ID == None or all([each == None for each in [GOOGLE_LOGIN, GOOGLE_PASSWORD, AUTH_TOKEN]]):
    raise Exception("config.py not updated")
```

Thank you for your answer.

**Comment by NeroBurner** [comment]
You can do that, but this check only throws an error if ANDROID_ID is empty or all of the listed (email, password and auth token) are empty. So it should be enough to set `AUTH_TOKEN = None`

**Comment by raspbeguy** [comment]
Works now, thanks.

**Comment by NeroBurner** [comment]
You're welcome. Happy to see someone using  my script :)
