### ISSUE TITLE
Error when running googlepayu

### ISSUE THREAD

**Issue by alex9434** [NeroBurner/googleplayupdater#5]
Hi all,

Great idea to develop the updater. However, I get the following error when running the program. Followed the instructions. Can anybody help me?

Traceback (most recent call last):
  File "/usr/local/bin/googleplayupdater", line 9, in <module>
    load_entry_point('googleplayupdater==0.1.2', 'console_scripts', 'googleplayupdater')()
  File "build/bdist.linux-x86_64/egg/googleplayupdater/gp_update.py", line 167, in main
  File "build/bdist.linux-x86_64/egg/googleplayupdater/gp_update.py", line 101, in update
  File "build/bdist.linux-x86_64/egg/googleplay_api/googleplay.py", line 243, in details
  File "build/bdist.linux-x86_64/egg/googleplay_api/googleplay.py", line 217, in executeRequestApi2
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b2.post2-py2.7.egg/google/protobuf/internal/python_message.py", line 770, in FromString
    message.MergeFromString(s)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b2.post2-py2.7.egg/google/protobuf/internal/python_message.py", line 1094, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.

**Comment by NeroBurner** [comment]
I've tried to use python 2.7.11 and protobuf-3.0.0b2 and protobuf-3.0.0b2.post2 and I wasn't able to reproduce the error.
How did you install googleplayupdater and protobuf?
Have you updated your config.py? Important fields are `ANDROID_ID`, `GOOGLE_LOGIN` and `GOOGLE_PASSWORD`

**Comment by NeroBurner** [comment]
can't reproduce
