### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by pyguy2020** [NeroBurner/googleplayupdater#6]
tried a few things, nothing seems to correct it. any ideas?

thanks ahead of time!

┌──(stryk3r㉿syshack3r)-[~/Desktop]
└─$ cd googleplayupdater-master
                                                                                                                    
┌──(stryk3r㉿syshack3r)-[~/Desktop/googleplayupdater-master]
└─$ ls
config_example.py  googleplay_api  googleplayupdater  LICENSE  README.md  setup.py
                                                                                                                    
┌──(stryk3r㉿syshack3r)-[~/Desktop/googleplayupdater-master]
└─$ chmod +x setup.py          
                                                                                                                    
┌──(stryk3r㉿syshack3r)-[~/Desktop/googleplayupdater-master]
└─$ ls
config_example.py  googleplay_api  googleplayupdater  LICENSE  README.md  setup.py
                                                                                                                    
┌──(stryk3r㉿syshack3r)-[~/Desktop/googleplayupdater-master]
└─$ python setup.py install        
running install
/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.11/dist-packages/test-easy-install-3997667.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.11/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

                                                                                                                    
┌──(stryk3r㉿syshack3r)-[~/Desktop/googleplayupdater-master]
└─$ pip install https://pypi.python.org/packages/source/p/protobuf/protobuf-3.0.0a3.tar.gz#md5=6674fa7452ebf066b767075db96a7ee0

Defaulting to user installation because normal site-packages is not writeable
Collecting https://pypi.python.org/packages/source/p/protobuf/protobuf-3.0.0a3.tar.gz#md5=6674fa7452ebf066b767075db96a7ee0
  Downloading https://pypi.python.org/packages/source/p/protobuf/protobuf-3.0.0a3.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.4/88.4 kB 958.8 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-ygqqdx__/setup.py", line 29, in <module>
          from distutils.command.build_py import build_py_2to3 as _build_py
      ImportError: cannot import name 'build_py_2to3' from 'distutils.command.build_py' (/usr/lib/python3/dist-packages/setuptools/_distutils/command/build_py.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by NeroBurner** [comment]
Sorry, I've not used this project for quite some time and should have archived it to show its staleness
